run:
  timeout: 5m

linters:
  enable:
    - govet
    - gofmt
    - ineffassign
    - unused
    - staticcheck
    - errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck