name: Health History Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Code and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          
      - name: Check golangci-lint installation
        run: |
          ls $(go env GOPATH)/bin
      
      - name: Add golangci-lint to PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run linters
        run: $(go env GOPATH)/bin/golangci-lint run --timeout 5m

      - name: Run tests
        run: |
          go test -v ./... -coverprofile=coverage.out
